# railing_structure_builder.py
# Builds CSS “sketches” of railing structures (geometry + infills).
#
# Run:
#   py railing_structure_builder.py
#
# Output:
#   railing_output/railing-structures.css
#   railing_output/railing-structures.json

from __future__ import annotations

import json
from pathlib import Path

OUT_DIR = Path("railing_output")

STRUCTURES = [
    # Aluminum / composite framed systems
    {
        "id": "aluminum_baluster",
        "label": "Standard Baluster",
        "notes": "Typical Westbury / Trex / TimberTech vertical balusters.",
        "infill": "baluster",
        "defaults": {"post_w": 14, "top_h": 14, "bottom_h": 10, "gap_top": 20, "gap_bottom": 22},
    },
    {
        "id": "aluminum_square_baluster_dense",
        "label": "Square Baluster (Dense)",
        "notes": "Slightly denser baluster spacing (common in aluminum).",
        "infill": "baluster_dense",
        "defaults": {"post_w": 14, "top_h": 14, "bottom_h": 10, "gap_top": 20, "gap_bottom": 22},
    },
    {
        "id": "cocktail_rail",
        "label": "Cocktail / Drink Rail",
        "notes": "Adds a wider top rail cap (Trex offers Cocktail Rail kits).",
        "infill": "baluster",
        "defaults": {"post_w": 14, "top_h": 18, "bottom_h": 10, "gap_top": 18, "gap_bottom": 22, "cap_h": 10},
    },
    # Cable
    {
        "id": "cable_horizontal",
        "label": "Horizontal Cable",
        "notes": "Horizontal cable infill; apply to metal/composite/wood frames.",
        "infill": "cable_horizontal",
        "defaults": {"post_w": 14, "top_h": 14, "bottom_h": 10, "gap_top": 20, "gap_bottom": 22},
    },
    {
        "id": "cable_vertical",
        "label": "Vertical Cable",
        "notes": "Vertical cable infill (Westbury VertiCable style).",
        "infill": "cable_vertical",
        "defaults": {"post_w": 14, "top_h": 14, "bottom_h": 10, "gap_top": 20, "gap_bottom": 22},
    },
    # Glass
    {
        "id": "glass_framed",
        "label": "Glass (Framed Panel)",
        "notes": "Framed glass panel look (Trex/TimberTech options).",
        "infill": "glass_panel",
        "defaults": {"post_w": 14, "top_h": 14, "bottom_h": 10, "gap_top": 20, "gap_bottom": 22},
    },
    {
        "id": "glass_frameless",
        "label": "Glass (Frameless Base Shoe)",
        "notes": "IG Railing style: frameless glass with base hardware.",
        "infill": "glass_frameless",
        "defaults": {"post_w": 0, "top_h": 0, "bottom_h": 12, "gap_top": 0, "gap_bottom": 12},
    },
    # Wood
    {
        "id": "wood_traditional",
        "label": "Wood Traditional",
        "notes": "Cedar / treated look with heavier members.",
        "infill": "baluster_wood",
        "defaults": {"post_w": 18, "top_h": 18, "bottom_h": 12, "gap_top": 18, "gap_bottom": 18},
    },
]

CSS = r"""
/* railing-structures.css
   Generated by railing_structure_builder.py
   Purpose: draw railing “structure” (posts/rails/infill) without images.
   Apply colors via CSS variables (palette layer).
*/

.railing{
  position: relative;
  width: 100%;
  height: var(--rail-h, 120px);

  /* Palette-provided base colors */
  --rail: var(--rail-color, #444);
  --post: var(--post-color, var(--rail));
  --hardware: var(--hardware-color, #bdbdbd);

  /* Shading */
  --hi: rgba(255,255,255,0.16);
  --lo: rgba(0,0,0,0.22);

  /* Default geometry (overridden per preset) */
  --post-w: 14px;
  --top-h: 14px;
  --bottom-h: 10px;
  --gap-top: 20px;
  --gap-bottom: 22px;
  --radius: 6px;

  /* Infill tuning */
  --baluster-w: 4px;
  --baluster-gap: 10px;

  --cable-w: 2px;
  --cable-gap: 10px;

  --glass-alpha-top: 0.32;
  --glass-alpha-bot: 0.06;
}

/* ---------- shared parts ---------- */
.railing__post{
  position:absolute;
  top: 0;
  bottom: 0;
  width: var(--post-w);
  border-radius: var(--radius);
  background:
    linear-gradient(180deg, var(--hi), transparent 35%),
    linear-gradient(90deg, var(--hi), transparent 35%, var(--lo)),
    var(--post);
  box-shadow: 0 6px 14px rgba(0,0,0,0.18);
}
.railing__post--left{ left: 0; }
.railing__post--right{ right: 0; }

.railing__top,
.railing__bottom{
  position:absolute;
  left: calc(var(--post-w) + 4px);
  right: calc(var(--post-w) + 4px);
  border-radius: var(--radius);
  background:
    linear-gradient(180deg, var(--hi), transparent 45%),
    linear-gradient(90deg, var(--hi), transparent 30%, var(--lo)),
    var(--rail);
}

.railing__top{
  top: var(--gap-top);
  height: var(--top-h);
  box-shadow: 0 4px 10px rgba(0,0,0,0.14);
}

.railing__bottom{
  bottom: var(--gap-bottom);
  height: var(--bottom-h);
  opacity: 0.96;
}

.railing__infill{
  position:absolute;
  left: calc(var(--post-w) + 8px);
  right: calc(var(--post-w) + 8px);
  top: calc(var(--gap-top) + var(--top-h) + 6px);
  bottom: calc(var(--gap-bottom) + var(--bottom-h) + 6px);
}

/* Optional top cap (cocktail/drink rail) */
.railing__cap{
  position:absolute;
  left: calc(var(--post-w) + 2px);
  right: calc(var(--post-w) + 2px);
  top: calc(var(--gap-top) - 6px);
  height: var(--cap-h, 0px);
  border-radius: calc(var(--radius) + 2px);
  background:
    linear-gradient(180deg, var(--hi), transparent 45%),
    linear-gradient(90deg, var(--hi), transparent 30%, var(--lo)),
    var(--rail);
  box-shadow: 0 4px 12px rgba(0,0,0,0.14);
  display:none;
}

/* ---------- infill styles ---------- */
.railing--infill-baluster .railing__infill{
  background:
    repeating-linear-gradient(
      90deg,
      rgba(0,0,0,0) 0px,
      rgba(0,0,0,0) var(--baluster-gap),
      color-mix(in srgb, var(--rail) 86%, black 14%) var(--baluster-gap),
      color-mix(in srgb, var(--rail) 86%, black 14%) calc(var(--baluster-gap) + var(--baluster-w))
    );
  filter: drop-shadow(0 2px 2px rgba(0,0,0,0.10));
}

.railing--infill-baluster-dense{ --baluster-gap: 8px; --baluster-w: 5px; }
.railing--infill-baluster-dense .railing__infill{ background:
  repeating-linear-gradient(
    90deg,
    rgba(0,0,0,0) 0px,
    rgba(0,0,0,0) var(--baluster-gap),
    color-mix(in srgb, var(--rail) 86%, black 14%) var(--baluster-gap),
    color-mix(in srgb, var(--rail) 86%, black 14%) calc(var(--baluster-gap) + var(--baluster-w))
  );
}

.railing--infill-cable-horizontal .railing__infill{
  background:
    repeating-linear-gradient(
      180deg,
      rgba(0,0,0,0) 0px,
      rgba(0,0,0,0) var(--cable-gap),
      color-mix(in srgb, var(--hardware) 88%, black 12%) var(--cable-gap),
      color-mix(in srgb, var(--hardware) 88%, black 12%) calc(var(--cable-gap) + var(--cable-w))
    );
}

.railing--infill-cable-vertical .railing__infill{
  background:
    repeating-linear-gradient(
      90deg,
      rgba(0,0,0,0) 0px,
      rgba(0,0,0,0) calc(var(--cable-gap) + 4px),
      color-mix(in srgb, var(--hardware) 88%, black 12%) calc(var(--cable-gap) + 4px),
      color-mix(in srgb, var(--hardware) 88%, black 12%) calc(var(--cable-gap) + 6px)
    );
}

.railing--infill-glass .railing__infill{
  border-radius: 10px;
  background:
    linear-gradient(180deg, rgba(255,255,255,var(--glass-alpha-top)), rgba(255,255,255,var(--glass-alpha-bot))),
    linear-gradient(90deg, rgba(255,255,255,0.20), rgba(255,255,255,0.02));
  border: 1px solid rgba(255,255,255,0.30);
  box-shadow: inset 0 0 0 1px rgba(0,0,0,0.06);
}

.railing--frameless{
  /* no posts/top rail; a base shoe and glass above */
  --post-w: 0px;
  --top-h: 0px;
  --gap-top: 0px;
  --gap-bottom: 12px;
}
.railing--frameless .railing__post,
.railing--frameless .railing__top{ display:none; }
.railing--frameless .railing__bottom{
  left: 0;
  right: 0;
  border-radius: 10px;
}
.railing--frameless .railing__infill{
  left: 0;
  right: 0;
  top: 0;
  bottom: calc(var(--gap-bottom) + var(--bottom-h) + 6px);
}

/* Wood preset tweaks */
.railing--wood{
  --hi: rgba(255,255,255,0.10);
  --lo: rgba(0,0,0,0.18);
  --radius: 5px;
}
"""

def build_structure_css() -> str:
    # In practice, we keep 1 file and use classes to toggle presets.
    # Your React component picks the right combo: base + preset + infill.
    return CSS.strip() + "\n"

def build_structure_json():
    return {
        "version": 1,
        "structures": STRUCTURES,
        "how_to_apply": {
            "base_class": "railing",
            "infill_classes": {
                "baluster": "railing--infill-baluster",
                "baluster_dense": "railing--infill-baluster-dense",
                "cable_horizontal": "railing--infill-cable-horizontal",
                "cable_vertical": "railing--infill-cable-vertical",
                "glass_panel": "railing--infill-glass",
                "glass_frameless": "railing--frameless railing--infill-glass",
                "baluster_wood": "railing--wood railing--infill-baluster",
            },
            "optional_cap": "Include <div class='railing__cap'/> and add class 'railing--has-cap' (you can enable via JS).",
        },
        "html_skeleton": """
<div class="railing railing--infill-baluster">
  <div class="railing__post railing__post--left"></div>
  <div class="railing__post railing__post--right"></div>
  <div class="railing__cap"></div>
  <div class="railing__top"></div>
  <div class="railing__bottom"></div>
  <div class="railing__infill"></div>
</div>
""".strip(),
    }

def main():
    OUT_DIR.mkdir(exist_ok=True)
    (OUT_DIR / "railing-structures.css").write_text(build_structure_css(), encoding="utf-8")
    (OUT_DIR / "railing-structures.json").write_text(json.dumps(build_structure_json(), indent=2), encoding="utf-8")
    print("Wrote", OUT_DIR / "railing-structures.css")
    print("Wrote", OUT_DIR / "railing-structures.json")

if __name__ == "__main__":
    main()