# wolf_palette_builder.py
# Build Wolf Serenity decking palette from Wolf's official "Serenity Decking Color Choices" page.
#
# Run:
#   py -m pip install requests beautifulsoup4 pillow lxml
#   py wolf_palette_builder.py
#
# Output:
#   wolf_output/wolf-decking.json
#   wolf_output/wolf-decking.css
#   wolf_output/swatches/*.png

import json
import re
from dataclasses import dataclass
from io import BytesIO
from pathlib import Path
from typing import Dict, List, Optional, Tuple
from urllib.parse import urljoin

import requests
from bs4 import BeautifulSoup
from PIL import Image


BASE = "https://www.wolfhomeproducts.com"
INDEX_URL = "https://www.wolfhomeproducts.com/product-category/serenity-decking-color-choices/"

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0 Safari/537.36"
    )
}


@dataclass
class Swatch:
    collection: str
    name: str
    product_url: str
    image_url: Optional[str]
    hex: Optional[str]


def slugify(s: str) -> str:
    s = s.lower().strip()
    s = re.sub(r"[®™]", "", s)
    s = re.sub(r"[^a-z0-9]+", "-", s)
    s = re.sub(r"-+", "-", s).strip("-")
    return s


def fetch_html(url: str, timeout: int = 30) -> str:
    r = requests.get(url, headers=HEADERS, timeout=timeout)
    r.raise_for_status()
    return r.text


def download_image(url: str, timeout: int = 30) -> Image.Image:
    r = requests.get(url, headers=HEADERS, timeout=timeout)
    r.raise_for_status()
    return Image.open(BytesIO(r.content)).convert("RGBA")


def average_color_center(img: Image.Image, center_crop: float = 0.60) -> Tuple[int, int, int]:
    w, h = img.size
    cw, ch = int(w * center_crop), int(h * center_crop)
    left = (w - cw) // 2
    top = (h - ch) // 2
    crop = img.crop((left, top, left + cw, top + ch))

    r_sum = g_sum = b_sum = n = 0
    for r, g, b, a in crop.getdata():
        if a < 20:
            continue
        r_sum += r
        g_sum += g
        b_sum += b
        n += 1
    if n == 0:
        return (128, 128, 128)
    return (r_sum // n, g_sum // n, b_sum // n)


def rgb_to_hex(rgb: Tuple[int, int, int]) -> str:
    return "#{:02X}{:02X}{:02X}".format(*rgb)


def extract_product_links(index_html: str) -> List[Tuple[str, str]]:
    """
    Returns list of (name, url) from the archive page.
    The open page shows "View product Ashland" etc.
    """
    soup = BeautifulSoup(index_html, "lxml")
    links = []
    for a in soup.find_all("a", href=True):
        txt = a.get_text(" ", strip=True)
        if not txt:
            continue
        m = re.match(r"View product\s+(.+)$", txt, flags=re.IGNORECASE)
        if not m:
            continue
        name = m.group(1).strip()
        url = urljoin(BASE, a["href"])
        links.append((name, url))

    # de-dupe by url
    seen = set()
    out = []
    for name, url in links:
        if url in seen:
            continue
        seen.add(url)
        out.append((name, url))
    return out


def og_image_url(product_html: str) -> Optional[str]:
    soup = BeautifulSoup(product_html, "lxml")
    tag = soup.find("meta", attrs={"property": "og:image"})
    if tag and tag.get("content"):
        return tag["content"].strip()
    # fallback: twitter image
    tag = soup.find("meta", attrs={"name": "twitter:image"})
    if tag and tag.get("content"):
        return tag["content"].strip()
    return None


def build_css(swatches: List[Swatch]) -> str:
    lines: List[str] = []
    lines.append("/* wolf-decking.css")
    lines.append("   Generated by wolf_palette_builder.py")
    lines.append("   Base vars + CSS-only light grain textures")
    lines.append("*/\n")

    lines.append(":root {")
    for sw in swatches:
        if not sw.hex:
            continue
        lines.append(f"  --wolf-serenity-{slugify(sw.name)}: {sw.hex};")
    lines.append("")
    lines.append("  --wolf-grain-alpha: 0.12;")
    lines.append("  --wolf-grain-size:  18px;")
    lines.append("  --wolf-board-sheen: 0.10;")
    lines.append("}\n")

    lines.append(":root {")
    lines.append("  --wolf-texture-template:")
    lines.append("    linear-gradient(0deg, rgba(255,255,255,var(--wolf-board-sheen)) 0%, rgba(255,255,255,0) 45%, rgba(0,0,0,0) 100%),")
    lines.append("    repeating-linear-gradient(135deg,")
    lines.append("      rgba(255,255,255,calc(var(--wolf-grain-alpha) * 0.55)) 0px,")
    lines.append("      rgba(255,255,255,0) 6px,")
    lines.append("      rgba(0,0,0,calc(var(--wolf-grain-alpha) * 0.45)) 12px),")
    lines.append("    repeating-linear-gradient(90deg,")
    lines.append("      rgba(0,0,0,calc(var(--wolf-grain-alpha) * 0.35)) 0px,")
    lines.append("      rgba(0,0,0,0) 2px,")
    lines.append("      rgba(255,255,255,calc(var(--wolf-grain-alpha) * 0.25)) 4px,")
    lines.append("      rgba(0,0,0,0) 7px);")
    lines.append("}\n")

    lines.append(":root {")
    for sw in swatches:
        if not sw.hex:
            continue
        key = f"wolf-serenity-{slugify(sw.name)}"
        lines.append(
            f"  --{key}-texture: var(--wolf-texture-template), "
            f"linear-gradient(0deg, var(--{key}), var(--{key}));"
        )
    lines.append("}\n")

    lines.append(".wolf-board {")
    lines.append("  background-size: 100% 100%, var(--wolf-grain-size) var(--wolf-grain-size), 10px 100%, 100% 100%;")
    lines.append("  background-blend-mode: overlay, overlay, overlay, normal;")
    lines.append("  border-radius: 10px;")
    lines.append("}\n")

    return "\n".join(lines)


def main():
    out_dir = Path("wolf_output")
    out_dir.mkdir(exist_ok=True)
    img_dir = out_dir / "swatches"
    img_dir.mkdir(exist_ok=True)

    print(f"Fetching Wolf color index: {INDEX_URL}")
    index_html = fetch_html(INDEX_URL)
    products = extract_product_links(index_html)
    print(f"Found {len(products)} Wolf Serenity colors")

    swatches: List[Swatch] = []
    for name, url in products:
        try:
            html = fetch_html(url)
            img = og_image_url(html)
            swatches.append(Swatch(collection="Serenity", name=name, product_url=url, image_url=img, hex=None))
        except Exception as e:
            print(f"  [err] {name}: {e}")

    for sw in swatches:
        if not sw.image_url:
            print(f"  [warn] No image URL for: {sw.name} ({sw.product_url})")
            continue
        try:
            im = download_image(sw.image_url)
            sw.hex = rgb_to_hex(average_color_center(im, center_crop=0.60))
            fname = f"serenity__{slugify(sw.name)}.png"
            im.save(img_dir / fname)
            print(f"  OK {sw.name}: {sw.hex}")
        except Exception as e:
            print(f"  [err] download/sample {sw.name}: {e}")

    grouped: Dict[str, List[dict]] = {"Serenity": []}
    for sw in sorted(swatches, key=lambda x: x.name):
        grouped["Serenity"].append({
            "name": sw.name,
            "slug": slugify(sw.name),
            "collection": sw.collection,
            "product_url": sw.product_url,
            "image_url": sw.image_url,
            "hex": sw.hex,
        })

    (out_dir / "wolf-decking.json").write_text(json.dumps(grouped, indent=2), encoding="utf-8")
    (out_dir / "wolf-decking.css").write_text(build_css(swatches), encoding="utf-8")
    print(f"Wrote {out_dir/'wolf-decking.json'}")
    print(f"Wrote {out_dir/'wolf-decking.css'}")
    print("Done.", out_dir.resolve())


if __name__ == "__main__":
    main()